import os

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile, status
from fastapi.responses import FileResponse
from pydantic import BaseModel

from app.api.deps import get_current_active_user
from app.models.user import User
from app.services.speech_service import SpeechService

router = APIRouter()


class SynthesisRequest(BaseModel):
    text: str
    voice: str = "alloy"


@router.post(
    "/transcribe",
    summary="Convert audio to text using Whisper",
)
async def transcribe_audio(
    file: UploadFile = File(...),
    current_user: User = Depends(get_current_active_user),
):
    """
    Accepts an audio file (mp3, wav, m4a, etc.) and returns the transcribed text.
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file uploaded.")

    service = SpeechService()
    try:
        text = await service.transcribe_audio(file)
        return {"text": text}
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Transcription failed: {str(e)}",
        )


@router.post(
    "/synthesize",
    summary="Convert text to speech using OpenAI TTS",
)
async def synthesize_speech(
    request: SynthesisRequest,
    current_user: User = Depends(get_current_active_user),
):
    """
    Accepts text and returns an audio file generated by OpenAI TTS.
    """
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty.")

    service = SpeechService()
    try:
        audio_path = await service.synthesize_speech(request.text, request.voice)
        
        # Cleanup task to remove the file after sending
        from starlette.background import BackgroundTask
        import os
        
        def remove_file(path: str):
            try:
                os.unlink(path)
            except Exception as exc:
                pass
                
        return FileResponse(
            path=audio_path,
            media_type="audio/mpeg",
            filename=audio_path.name,
            background=BackgroundTask(remove_file, str(audio_path)),
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Synthesis failed: {str(e)}",
        )
